apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-emp-perf-dev
  labels:
    app: emp-perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-perf
  template:
    metadata:
      labels:
        app: emp-perf
        role: rolling-update
    spec:
      containers:
      - name: emp-perf
        image: gishann/emp-perf:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: emp-perf
  name: emp-perf-app-dev
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: emp-perf
  type: LoadBalancer