apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-emp-perf-be-test
  labels:
    app: emp-perf-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-perf-be
  template:
    metadata:
      labels:
        app: emp-perf-be
        role: rolling-update
    spec:
      containers:
      - name: emp-perf-be
        image: gishann/emp-perf-be:1.0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-emp-perf-fe-test
  labels:
    app: emp-perf-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emp-perf-fe
  template:
    metadata:
      labels:
        app: emp-perf-fe
        role: rolling-update
    spec:
      containers:
      - name: emp-perf-fe
        image: gishann/emp-perf-fe:1.0
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: emp-perf
  name: emp-perf-app-test
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: emp-perf
  type: LoadBalancer