apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-emp-perf-app-test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        role: rolling-update
    spec:
      containers:
      - name: nginx
        image: gishann/emp-perf
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: emp-perf-app-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer